# Generated by Django 5.0.2 on 2024-05-14 07:14

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.vid_upload),
        ),
    ]
